### ISSUE TITLE
Suggestion: Automatically add trailling slash to `index_url` if missing

### ISSUE THREAD

**Issue by carlosperate** [wheel-next/wheel-stub#12]
Otherwise `urllib.parse.urljoin()` removes the base URL path until the last slash, which results in a bad URL, and the error thrown is about not finding the page.

<details><summary>Expand error message</summary>
<p>

```
Processing ./arm_none_eabi_gcc_toolchain-9.2.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [112 lines of output]
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/wheel.py", line 245, in download_wheel
          return download_manual(wheel_directory, distribution, version, config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/wheel.py", line 175, in download_manual
          raise RuntimeError(f"Failed to open project URL {project_url}") from e
      Traceback (most recent call last):
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/wheel.py", line 173, in download_manual
          index_response = urlopen_with_retry(project_url)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/wheel.py", line 92, in urlopen_with_retry
          return urlopen(url, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 557, in error
          result = self._call_chain(*args)
                   ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 749, in http_error_302
          return self.parent.open(new, timeout=req.timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 557, in error
          result = self._call_chain(*args)
                   ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 749, in http_error_302
          return self.parent.open(new, timeout=req.timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "/Users/microbit-carlos/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 404: Not Found
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/wheel.py", line 245, in download_wheel
          return download_manual(wheel_directory, distribution, version, config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/wheel.py", line 175, in download_manual
          raise RuntimeError(f"Failed to open project URL {project_url}") from e
      RuntimeError: Failed to open project URL https://carlosperate.github.io/arm-none-eabi-gcc-toolchain/
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/microbit-carlos/workspace/carlos/arm-none-eabi-gcc-py-package/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/microbit-carlos/workspace/carlos/arm-none-eabi-gcc-py-package/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/microbit-carlos/workspace/carlos/arm-none-eabi-gcc-py-package/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/wheel.py", line 247, in download_wheel
          report_install_failure(distribution, version, config, exception_context)
        File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/pip-build-env-bdpoudrw/overlay/lib/python3.11/site-packages/wheel_stub/error.py", line 67, in report_install_failure
          raise InstallFailedError(
      wheel_stub.error.InstallFailedError:
      *******************************************************************************
      
      The installation of arm-none-eabi-gcc-toolchain for version 9.2.1 failed.
      
      This is a special placeholder package which downloads a real wheel package
      from https://carlosperate.github.io/arm-none-eabi-gcc-py-package. If https://carlosperate.github.io/arm-none-eabi-gcc-py-package is not reachable, we
      cannot download the real wheel file to install.
      
      You might try installing this package via
      ```
      $ pip install --extra-index-url https://carlosperate.github.io/arm-none-eabi-gcc-py-package arm-none-eabi-gcc-toolchain
      ```
      
      Here is some debug information about your platform to include in any bug
      report:
      
      Python Version: CPython 3.11.7
      Operating System: Darwin 21.6.0
      CPU Architecture: x86_64
      
      *******************************************************************************
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

</p>
</details> 

There is actually a comment warning about this, but should be a very small fix, and I'd be happy to submit a PR:
https://github.com/wheel-next/wheel-stub/blob/3f7a41d15086e1d11f43b4c1d245987993bfefa2/src/wheel_stub/wheel.py#L160-L161

PEP 503 indicates the server should always redirect URLs to the version with the trailing slash, so it should work in theory with all compliant servers.

**Comment by emmatyping-nv** [comment]
> PEP 503 indicates the server should always redirect URLs to the version with the trailing slash

Unfortunately, our server does not do this. This is something that I hope to fix eventually, but for now wheel-stub needs to ensure that the project/index requests end in a /. I think the patch in #13 should be fine, however.
