### ISSUE TITLE
Python < 3.12 compability: `AttributeError: 'TarInfo' object has no attribute 'replace'`

### ISSUE THREAD

**Issue by carlosperate** [wheel-next/wheel-stub#5]
When trying to build the README demo sdist on Python 3.10 I get the following error:

```
$ PIP_FIND_LINKS=`pwd`/../dist python -m build --sdist --config-setting source_wheel=nvidia_cuda_runtime_cu12-12.4.99-py3-none-manylinux2014_x86_64.whl
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (wheel-stub)
* Getting build dependencies for sdist...
* Building sdist...
Traceback (most recent call last):
  File "/Users/microbit-carlos/Library/Application Support/hatch/env/pip-compile/wheel-stub/CLj2ycj5/wheel-stub/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/Users/microbit-carlos/Library/Application Support/hatch/env/pip-compile/wheel-stub/CLj2ycj5/wheel-stub/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/microbit-carlos/Library/Application Support/hatch/env/pip-compile/wheel-stub/CLj2ycj5/wheel-stub/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 304, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/build-env-jbrgizs5/lib/python3.10/site-packages/wheel_stub/buildapi.py", line 38, in build_sdist
    return SDistBuilder(pathlib.Path(sdist_directory), config_settings).build().name
  File "/private/var/folders/12/nh0jjpzj7qs9njm_nx5b48p40000gn/T/build-env-jbrgizs5/lib/python3.10/site-packages/wheel_stub/sdist.py", line 151, in build
    pyproj_tarinfo = pyproj_tarinfo.replace(
AttributeError: 'TarInfo' object has no attribute 'replace'

ERROR Backend subprocess exited when trying to invoke build_sdist
```

Looks like `TarInfo.replace()` was added in Python 3.12: https://docs.python.org/3/library/tarfile.html#tarfile.TarInfo.replace
https://github.com/wheel-next/wheel-stub/blob/3f7a41d15086e1d11f43b4c1d245987993bfefa2/src/wheel_stub/sdist.py#L150-L153

And this project is currently listed as 3.8+:
https://github.com/wheel-next/wheel-stub/blob/3f7a41d15086e1d11f43b4c1d245987993bfefa2/pyproject.toml#L12

**Comment by carlosperate** [comment]
I was a bit confused that this worked in the CI (https://github.com/wheel-next/wheel-stub/pull/10), turns out this was introduced in Python 3.12 and in the following "micro" releases of Python [3.8.17](https://docs.python.org/3.8/library/tarfile.html#tarfile.TarInfo.replace), [3.9.17](https://docs.python.org/3.9/library/tarfile.html#tarfile.TarInfo.replace), [3.10.12](https://docs.python.org/3.10/library/tarfile.html#tarfile.TarInfo.replace),  and [3.11.4](https://docs.python.org/3.11/library/tarfile.html#tarfile.TarInfo.replace), which were released all around June 2023.

That's a bit annoying, I probably won't be the only one with slightly old Python versions, as it'll essentially fail in any Python release before June 2023.

**Comment by emmatyping-nv** [comment]
Sorry, I was out when you posted this (and your other issues). I'll take a look at fixing this.
